name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.1.0

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npx cypress run
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
